#!/usr/bin/env python

class PackageManagerError(Exception):
    ''' Base class for exceptions generated by SONiC package manager '''

    pass


class PackageNotFoundError(PackageManagerError):
    ''' Package not found in package database exception '''

    def __init__(self, name):
        self._name = name

    def __str__(self):
        return 'Package {} is not found in packages database'.format(self._name)

class PackageInstallationError(PackageManagerError):
    pass

